---
- hosts: database
  gather_facts: yes
  become: true
  become_method: sudo
#  become_user: root
  
  vars:
#    postgresql_version: "14"
    postgresql_bin_path: "/usr/lib/postgresql/{{ postgresql_version }}/bin"
#    postgresql_data_dir: "/var/lib/postgresql/{{ postgresql_version }}/main"
    ansible_ssh_pipelining: true
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name:
          - postgresql
          - postgresql-contrib
          - libpq-dev
          - python3-psycopg2
        state: present

    - name: Check if PostgreSQL is initialized
      ansible.builtin.stat:
        path: "{{ postgresql_data_dir }}/pg_hba.conf"
      register: postgres_data

    - name: Empty data dir
      ansible.builtin.file:
        path: "{{ postgresql_data_dir }}"
        state: absent
      when: not postgres_data.stat.exists


    - name: Start and enable service
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: true


- hosts: app
  gather_facts: yes
  become: true
  become_method: sudo
  ignore_errors: True
  tasks:
  - name: install docker on ubuntu
    block:
          - name: install pkg
            apt:
                    pkg:
                            - apt-transport-https
                            - ca-certificates
                            - curl
                            - software-properties-common
                            - python3-pip
                            - virtualenv
                            - python3-setuptools
                    state: latest
                    update_cache: true
          - name: add key
            apt_key:
                    url: https://download.docker.com/linux/ubuntu/gpg
                    state: present

          - name: add docker repository
            apt_repository:
                    repo: deb https://download.docker.com/linux/ubuntu focal stable
                    state: present

          - name: docker.io install
            apt:
                    name: docker.io
                    state: latest
                    update_cache: true


          - name: install docker
            apt:
                    name:
                            - docker
                            - docker.io
                            - docker-compose
                            - docker-registry
                    state: latest
                    update_cache: true

                    
    when: ansible_os_family == "Debian"

  - name: install docker on centos
    block:
          - name: install utilits
            yum:
                    name:
                            - yum-utils
                            - device-mapper-persistent-data
                            - lvm2
                    state: latest

          - name: docker repo
            yum_repository:
                    name: docker
                    description: repo for docker
                    baseurl: https://download.docker.com/linux/centos/8/x86_64/stable/
                    gpgcheck: no

          - name: install docker
            yum:
                    name: docker-ce 

    when: ansible_os_family == "RedHat"  

